const projects = [
  {
    title: "Game Hub",
    category: 2,
    image: "/images/gamehub.png",
    languages: "react , typescript and chakra ui",
    url: "https://reactgamehub.vercel.app/",
  },
  {
    title: "MEC stock pos",
    category: 3,
    image: "/images/mec.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://mec.hmmdemo.com/",
  },
  {
    title: "Grand Winner Printing",
    category: 3,
    image: "/images/gwinner.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://gwinner.hmm-staging.com/",
  },
  {
    title: "Yellow Pages UI",
    category: 1,
    image: "/images/yellowF.png",
    languages: "Figma",
    url: "#",
  },
  {
    title: "Bagan Management Institute",
    category: 2,
    image: "/images/bmi.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "http://baganmanagementinstitute.com",
  },
  {
    title: "Ye' Ta Khon Group UI",
    category: 1,
    image: "/images/ytkF.png",
    languages: "Figma",
    url: "#",
  },
  {
    title: "Maxx Vape UI",
    category: 1,
    image: "/images/maxxvapeF.png",
    languages: "Figma",
    url: "#",
  },
  {
    title: "Asonemart Ecommerce",
    category: 3,
    image: "/images/asonemart.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://asonemart.com/",
  },
  {
    title: "Ye' Ta Khon Group",
    category: 2,
    image: "/images/ytk.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://yetakhongroup.com",
  },
  {
    title: "Shwe Mi Furniture",
    category: 2,
    image: "/images/shwemi.png",
    languages: "html, css, js, bootstrap and php",
    url: "http://shwemifurniture.com/",
  },
  {
    title: "Stu Express",
    category: 3,
    image: "/images/stuexpress.png",
    languages: "tailwind, laravel and filament php",
    url: "http://stuexpress.hmm-staging.com",
  },
  {
    title: "Innopex Myanmar",
    category: 2,
    image: "/images/innopex.png",
    languages: "html, css, js, bootstrap, php and wordpress",
    url: "https://innopexmyanmar.com",
  },
  {
    title: "BMI UI",
    category: 1,
    image: "/images/bmiF.png",
    languages: "Figma",
    url: "#",
  },
  {
    title: "Myanmar Brewery",
    category: 3,
    image: "/images/mm-beer.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "http://myanmar-brewery.com/",
  },
  {
    title: "Maung Sein Win",
    category: 2,
    image: "/images/maungsw.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://www.maungseinwinandbrothers.com/",
  },
  {
    title: "Shwe Mi Furniture UI",
    category: 1,
    image: "/images/shwemiF.png",
    languages: "Figma",
    url: "#",
  },
  {
    title: "Maxx-vape",
    category: 2,
    image: "/images/maxxvape.png",
    languages: "html, css, js, bootstrap and php",
    url: "https://maxx-vape.com",
  },
  {
    title: "Moe Kaung Myay",
    category: 2,
    image: "/images/mkm.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://moekaungmyay.com/",
  },
  {
    title: "Yellow Pages UI",
    category: 2,
    image: "/images/yellowpages.png",
    languages: "html, css, js, jquery, bootstrap and php",
    url: "#",
  },
];

export default projects;
