const projects = [
  {
    id: 1,
    title: "MEC stock pos",
    category: 3,
    image: "/public/images/mec.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://mec.hmmdemo.com/",
  },
  {
    id: 2,
    title: "Grand Winner Printing",
    category: 3,
    image: "/public/images/gwinner.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://gwinner.hmm-staging.com/",
  },
  {
    id: 3,
    title: "Yellow Pages UI",
    category: 1,
    image: "/public/images/yellowF.png",
    languages: "Figma",
    url: "",
  },
  {
    id: 4,
    title: "Bagan Management Institute",
    category: 2,
    image: "/public/images/bmi.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "http://baganmanagementinstitute.com",
  },
  {
    id: 5,
    title: "Ye' Ta Khon Group UI",
    category: 1,
    image: "/public/images/ytkF.png",
    languages: "Figma",
    url: "",
  },
  {
    id: 6,
    title: "Maxx Vape UI",
    category: 1,
    image: "/public/images/maxxvapeF.png",
    languages: "Figma",
    url: "",
  },
  {
    id: 7,
    title: "Asonemart Ecommerce",
    category: 3,
    image: "/public/images/asonemart.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "https://asonemart.com/",
  },
  {
    id: 8,
    title: "Ye' Ta Khon Group",
    category: 2,
    image: "/public/images/ytk.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://yetakhongroup.com",
  },
  {
    id: 9,
    title: "Shwe Mi Furniture",
    category: 2,
    image: "/public/images/shwemi.png",
    languages: "html, css, js, bootstrap and php",
    url: "http://shwemifurniture.com/",
  },
  {
    id: 10,
    title: "Stu Express",
    category: 3,
    image: "/public/images/stuexpress.png",
    languages: "tailwind, laravel and filament php",
    url: "http://stuexpress.hmm-staging.com",
  },
  {
    id: 11,
    title: "Innopex Myanmar",
    category: 2,
    image: "/public/images/innopex.png",
    languages: "html, css, js, bootstrap, php and wordpress",
    url: "https://innopexmyanmar.com",
  },
  {
    id: 12,
    title: "BMI UI",
    category: 1,
    image: "/public/images/bmiF.png",
    languages: "Figma",
    url: "",
  },
  {
    id: 13,
    title: "Myanmar Brewery",
    category: 3,
    image: "/public/images/mm-beer.png",
    languages: "html, css, js, bootstrap, ajax, jquery, php and laravel",
    url: "http://myanmar-brewery.com/",
  },
  {
    id: 14,
    title: "Maung Sein Win",
    category: 2,
    image: "/public/images/maungsw.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://www.maungseinwinandbrothers.com/",
  },
  {
    id: 15,
    title: "Shwe Mi Furniture UI",
    category: 1,
    image: "/public/images/shwemiF.png",
    languages: "Figma",
    url: "",
  },
  {
    id: 16,
    title: "Maxx-vape",
    category: 2,
    image: "/public/images/maxxvape.png",
    languages: "html, css, js, bootstrap and php",
    url: "https://maxx-vape.com",
  },
  {
    id: 17,
    title: "Moe Kaung Myay",
    category: 2,
    image: "/public/images/mkm.png",
    languages: "html, css, js, bootstrap, jquery, php and wordpress",
    url: "https://moekaungmyay.com/",
  },
  {
    id: 18,
    title: "Yellow Pages UI",
    category: 2,
    image: "/public/images/yellowpages.png",
    languages: "html, css, js, jquery, bootstrap and php",
    url: "",
  },
];

export default projects;
